apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: my-secret
      containers:
      - name: redis
        image: gcr.io/sabrinnasr2050/redis:latest
        ports:
        - containerPort: 6379
